# version: '3.8'

# services:
#   indexapi:
#     build: .
#     container_name: indexapi-container
#     ports:
#       - "3000:80"
#     restart: unless-stopped


version: '3.8'

services:
  indexapi:
    build:
      context: .
    image: ${DOCKER_USERNAME}/indexapi:latest
    ports:
      - "8080:8080"  # Exposing port 8080 (for example) for the application
    volumes:
      - .:/app      # Mounting the current directory to the container's /app directory
    environment:
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
